### PR TITLE
NewRequest & sendRequest methods of Instagram structure return []byte

### PR DESCRIPTION
**Pull request by CreditSuisse1**
The methods return both []byte and err + refactoring related with errors, that will never be called

In some cases calling json.Marshal will never return ```err != nil```, so I have changed it to blank identifier

### CODE REVIEW

**Comment by ahmdrz** [comment]
@CreditSuisse1 Thanks Man , But you can check via test files.

**Comment by ahmdrz** [comment]
All of tests passed :smile: , Nice work

https://travis-ci.org/ahmdrz/goinsta/jobs/194820696

**Comment by CreditSuisse1** [comment]
Yeah, I tested via test files too, but this it not 100% covered project, that is why I wrote first comment:)

**Comment by ahmdrz** [comment]
@CreditSuisse1 You right , Can you help me to improve test files ?

**Comment by CreditSuisse1** [comment]
I will take a look

**Pull request merged**
