### PR TITLE
Export Proxy

### PR DESCRIPTION
**Pull request by jaynagpaul**
Need this to be exported to change the proxy without generating a whole new struct.
It is backwards compatible.
Is also the 200th commit if merged 🎉

### CODE REVIEW

**Comment by ahmdrz** [comment]
Hi @jaynagpaul
Thank you for new PR.
I don't like backwards compatible !
Can we fix this problem with adding new method ?
Something like `insta.ChangeProxy()`.

**Comment by ahmdrz** [comment]
Also I don't know how many people use goinsta with proxy option

**Comment by jaynagpaul** [comment]
Backwards compatible is good though, it only adds a new field from the point of the end user, doesn't change or remove one.

**Comment by ahmdrz** [comment]
Your right. Sorry for my mistake.
Thank you for 200th commit :smile: 

Good luck.

**Pull request merged**
