### PR TITLE
search location

### PR DESCRIPTION
**Pull request by rakd**
add SearchLocation()
@ahmdrz

### CODE REVIEW

**Comment by ahmdrz** [comment]
Hi , Please change your code then make new pull request.
If `lat` or `lng` was empty , you have return an error.

**Comment by rakd** [comment]
thanks for review. i've fixed it, please have a look. @ahmdrz

**Comment by ahmdrz** [comment]
This branch has conflicts that must be resolved. :(

**Comment by rakd** [comment]
oh, let me check...

**Comment by rakd** [comment]
solved. @ahmdrz

**Comment by ahmdrz** [comment]
Thank you again

**Pull request merged**
