### PR TITLE
maybe fix Travis test...

### PR DESCRIPTION
**Pull request by GhostRussia**

### CODE REVIEW

**Comment by GhostRussia** [comment]
:-(

**Comment by ahmdrz** [comment]
:(
goinsta_test.go:623: Invalid status code {"message": "Please wait a few minutes before you try again.", "status": "fail"}

**Comment by GhostRussia** [comment]
Restart the test after an hour, it can help.
The error is not in the tests, they work, but the API does not allow testing. :-(

**Comment by ahmdrz** [comment]
Many days ago i wrote private and public tests ...
And I received these errors.
I remove those methods...
I think we can ignore  private and public tests

**Comment by GhostRussia** [comment]
Okay

**Comment by ahmdrz** [comment]
All tests passed

**Pull request merged**
