### PR TITLE
Added 5 seconds to sleep to avoid to be logged-out

### LINKED ISSUE #104: The account is logged out when get followers
I want to get followers from a certain user so I did:

```go
package main

import (
        "fmt"

        "github.com/ahmdrz/goinsta"
)

func main() {
        insta := goinsta.New("username", "password")

        if err := insta.Login(); err != nil {
                fmt.Println(err)
                return
        }

        fmt.Println("logged-in")
        defer insta.Logout()

        userResponse, err := insta.GetUserByUsername("unconventionalbaker")
        if err != nil {
                fmt.Println(err)
                return
        }
        fmt.Println("I took the ID")
        userID := userResponse.User.ID
        followersResponse, err := insta.TotalUserFollowers(userID)
        if err != nil {
                fmt.Println(err)
                return
        }

        fmt.Println("I got followers")

        for _, f := range followersResponse.Users {
                fmt.Println(f.Username)
        }
}
```
This print
```
logged-in
I took the ID
The account is logged out
```
After `I took the ID` I have to wait 1 minute and after that: `The account is logged out`, I thought due the large amount of followers of that user so now the question: How can I get the list of that account's followers?

Thanks

### PR DESCRIPTION
**Pull request by dlion**
Fixed #104

### CODE REVIEW

**Comment by ahmdrz** [comment]
Hi @dlion , I think it's not a good way to fix your problem.
@themester What's your idea ?

**Comment by dlion** [comment]
@ahmdrz Instagram between requests wants a delay time to block spammers. A minimum delay  is 5 seconds and with my fix I can take all followers I want without problems (maybe you can add a delay time in the request function), if you know a better solution let me know, I'm interested to fix it. 😊

**Comment by ahmdrz** [comment]
> Instagram between requests wants a delay time to avoid spammers

That's the reason of my delays in test files.
I think it can be 3 seconds. But ...
For a member with more than 2K followers , It will take too long to fetch all of followers.
I think it's better to implement it using `generator patterns` or something else like it.
What's your idea ?

**Comment by dlion** [comment]
> I think it can be 3 seconds. But ...
I read about 5 seconds here: https://github.com/mgp25/Instagram-API/issues/1710#issuecomment-347415959


> For a member with more than 2K followers , It will take too long to fetch all of followers.

Well I thought to save all followers to a DB the first time and yes, to get all followers my code takes a lot of time.
I thought to implement a retry function or a generator pattern but how to be sure that Instagram doesn't block any kind of request from the same source? (even using goroutines)

**Comment by themester** [comment]
@dlion This pull request won't be accepted for the following reasons:
1.- We are working on a new API (you can check it out at the alpha branch). This new API implements paging methods which allows pagination using a comfortable function (Next) and gives you control to call your Sleep function between calls.
2.- Personally I do not think the TotalUserFollow* functions are necessary (it's an unneeded automation) unless you have a small number of followers/following.
3.- If you want to use this function with Sleep call you can use UserFollow* functions.

**Comment by themester** [comment]
@dlion This pull request won't be accepted for the following reasons:
1.- We are working on a new API (you can check it out at the alpha branch). This new API implements paging methods which allows pagination using a comfortable function (Next) and gives you control to call your Sleep function between calls.
2.- Personally I do not think the TotalUserFollow* functions are necessary (it's an unneeded automation) unless you have a small number of followers/following.
3.- If you want to use this function with Sleep call you can use UserFollow* functions.

**Comment by themester** [comment]
https://godoc.org/gopkg.in/ahmdrz/goinsta.v2

**Pull request closed without merging**
