### PR TITLE
Constacts synchronization added

### PR DESCRIPTION
**Pull request by AmaHacka**
Ability to search users by emails and mobile phones

### CODE REVIEW

**Comment by ahmdrz** [comment]
Hi,
Please remove `fmt.Println(string(body))` in your code.

**Comment by AmaHacka** [comment]
@ahmdrz done

**Comment by ahmdrz** [comment]
Thank you @AmaHacka

**Comment by wakenn** [comment]
This now returns: "warning":"This endpont is deprecated, please use find_v2"

**Comment by AmaHacka** [comment]
Last IG application for Android use this method... @wakenn 
Official app get this warning too.

**Pull request merged**
