### PR TITLE
Add SetCookies to use this API without Login. 

### PR DESCRIPTION
**Pull request by rakd**
It might not be suitable, but i'd like to use it personally. I don't mind if it'll be rejected. @ahmdrz

### CODE REVIEW

**Comment by ahmdrz** [comment]
Can you explain more why you want this ?

**Comment by rakd** [comment]
hi @ahmdrz 

Now i'm preparing a web app which is like auto-liker for my friends.
They need to input their Instagram password on the app, but I don't want to keep their Instagram password cuz of security. I'd like to store only 

- cookies
- goinsta.Instagram.Informations

so that, I can access&like instead of them.

GetSessions() enabled us to get cookies, so I can get cookies tho,,, I was not able to find a way to set cookies. so I've prepared SetCookies().

**Comment by ahmdrz** [comment]
Hi
Seems good , one of my TODOs is make backup from current informations.
Please note to encrypt sessions and save them.
By the way
Thank you :)

**Comment by rakd** [comment]
👍

**Pull request merged**
