### PR TITLE
add 2 functions after login

### LINKED ISSUE #14: Timeline() giving me old feed
I have created this user in Instagram and followed a few public celebrities normally from my phone. After Login() and then Timeline() from Go using your lib everything works just fine and I can fetch feed and paginate. But when I call run it again Timeline() keeps giving me the same feed again and again.

I realized after opening Instagram timeline on my phone and viewing new posts once, next time I run the Go program, Timeline func fetches all the new feeds successfully and I can paginate and everything works just fine.
It feels like opening instagram on phone triggers sth that let Timeline() fetch new items not the old cached ones.
Have you ever experienced this or is it supposed to  happen?

### PR DESCRIPTION
**Pull request by sourcesoft**
Trying to fix #14 

Adding `syncFeatures` and `autoCompleteUserList` inspired by [Instagram-api](https://github.com/mgp25/Instagram-API).

Currently gives me an error I can't figure out:
`panic: Invalid status code {"message": "invalid request", "status": "fail"}`

We can take a good look at it here in this PR

### CODE REVIEW

**Comment by sourcesoft** [comment]
functions in implemented in PHP port

```
public function syncFeatures($prelogin = false)
    {
        if ($prelogin) {
            return $this->request('qe/sync/')
            ->requireLogin(true)
            ->addPost('id', SignatureUtils::generateUUID(true))
            ->addPost('experiments', Constants::LOGIN_EXPERIMENTS)
            ->getResponse(new SyncResponse());
        } else {
            return $this->request('qe/sync/')
            ->addPost('_uuid', $this->uuid)
            ->addPost('_uid', $this->username_id)
            ->addPost('_csrftoken', $this->token)
            ->addPost('id', $this->username_id)
            ->addPost('experiments', Constants::EXPERIMENTS)
            ->getResponse(new SyncResponse());
        }
    }
```

```
    public function autoCompleteUserList()
    {
        $this->request('friendships/autocomplete_user_list/')
        ->setCheckStatus(false)
        ->addParams('version', '2')
        ->getResponse(new autoCompleteUserListResponse());
    }
```

**Comment by ahmdrz** [comment]
Thank you bro...
After adding to methods , did you have any problem in fetching new feeds ?

**Comment by sourcesoft** [comment]
Gives me this while Login:
```
panic: Invalid status code {"message": "invalid request", "status": "fail"}
```
happens [here](https://github.com/ahmdrz/goinsta/pull/15/files#diff-b6d33ead2ad4ef12fddf99bf0f7b455eR157)

**Comment by ahmdrz** [comment]
@sourcesoft 
```php
    public function syncFeatures($prelogin = false)
    {
        if ($prelogin) {
            return $this->request('qe/sync/')
            ->requireLogin(true)
            ->addPost('id', SignatureUtils::generateUUID(true))
            ->addPost('experiments', Constants::LOGIN_EXPERIMENTS)
            ->getResponse(new SyncResponse());
        } else {
            return $this->request('qe/sync/')
            ->addPost('_uuid', $this->uuid)
            ->addPost('_uid', $this->username_id)
            ->addPost('_csrftoken', $this->token)
            ->addPost('id', $this->username_id)
            ->addPost('experiments', Constants::EXPERIMENTS)
            ->getResponse(new SyncResponse());
        }
    }
```
is not the same as 
```go
   _, err = insta.sendRequest("qe/sync/", generateExperiments(), false)
   if err != nil {
     panic(err)
   }
```

You did not pass `csrftoken` and etc...

**Comment by sourcesoft** [comment]
added `_uuid`, `_uid`, `_csrftoken` still getting the exact same error.
````
experiments=ig_android_ad_holdout_16m5_universe,ig_android_progressive_jpeg,ig_creation_growth_holdout,ig_android_oppo_app_badging,ig_android_ad_remove_username_from_caption_universe,ig_android_enable_share_to_whatsapp,ig_android_direct_drawing_in_quick_cam_universe,ig_android_ad_always_send_ad_attribution_id_universe,ig_android_universe_video_production,ig_android_direct_plus_button,ig_android_ads_heatmap_overlay_universe,ig_android_http_stack_experiment_2016,ig_android_infinite_scrolling,ig_fbns_blocked,ig_android_post_auto_retry_v7_21,ig_fbns_push,ig_android_video_playback_bandwidth_threshold,ig_android_direct_link_preview,ig_android_direct_typing_indicator,ig_android_preview_capture,ig_android_feed_pill,ig_android_profile_link_iab,ig_android_story_caption,ig_android_network_cancellation,ig_android_histogram_reporter,ig_android_anrwatchdog,ig_android_search_client_matching,ig_android_follow_request_text_buttons,ig_android_feed_zoom,ig_android_drafts_universe,ig_android_disable_comment,ig_android_user_detail_endpoint,ig_android_os_version_blocking,ig_android_blocked_list,ig_android_event_creation,ig_android_high_res_upload_2,ig_android_2fac,ig_android_mark_reel_seen_on_Swipe_forward,ig_android_comment_redesign,ig_android_ad_sponsored_label_universe,ig_android_mentions_dismiss_rule,ig_android_disable_chroma_subsampling,ig_android_share_spinner,ig_android_video_reuse_surface,ig_explore_v3_android_universe,ig_android_media_favorites,ig_android_nux_holdout,ig_android_insta_video_universe,ig_android_search_null_state,ig_android_universe_reel_video_production,liger_instagram_android_univ,ig_android_direct_emoji_picker,ig_feed_holdout_universe,ig_android_direct_send_auto_retry_universe,ig_android_samsung_app_badging,ig_android_disk_usage,ig_android_business_promotion,ig_android_direct_swipe_to_inbox,ig_android_feed_reshare_button_nux,ig_android_react_native_boost_post,ig_android_boomerang_feed_attribution,ig_fbns_shared,ig_fbns_dump_ids,ig_android_react_native_universe,ig_show_promote_button_in_feed,ig_android_ad_metadata_behavior_universe,ig_android_video_loopcount_int,ig_android_inline_gallery_backoff_hours_universe,ig_android_rendering_controls,ig_android_profile_photo_as_media,ig_android_async_stack_image_cache,ig_video_max_duration_qe_preuniverse,ig_video_copyright_whitelist,ig_android_render_stories_with_content_override,ig_android_ad_intent_to_highlight_universe,ig_android_swipe_navigation_x_angle_universe,ig_android_disable_comment_public_test,ig_android_profile,ig_android_direct_blue_tab,ig_android_enable_share_to_messenger,ig_android_fetch_reel_tray_on_resume_universe,ig_android_promote_again,ig_feed_event_landing_page_channel,ig_ranking_following,ig_android_pending_request_search_bar,ig_android_feed_ufi_redesign,ig_android_pending_edits_dialog_universe,ig_android_business_conversion_flow_universe,ig_android_show_your_story_when_empty_universe,ig_android_ad_drop_cookie_early,ig_android_app_start_config,ig_android_fix_ise_two_phase,ig_android_ppage_toggle_universe,ig_android_pbia_normal_weight_universe,ig_android_profanity_filter,ig_ios_su_activity_feed,ig_android_search,ig_android_boomerang_entry,ig_android_mute_story,ig_android_inline_gallery_universe,ig_android_ad_remove_one_tap_indicator_universe,ig_android_view_count_decouple_likes_universe,ig_android_contact_button_redesign_v2,ig_android_periodic_analytics_upload_v2,ig_android_send_direct_typing_indicator,ig_android_ad_holdout_16h2m1_universe,ig_android_react_native_comment_moderation_settings,ig_video_use_sve_universe,ig_android_inline_gallery_no_backoff_on_launch_universe,ig_android_immersive_viewer,ig_android_discover_people_icon,ig_android_profile_follow_back_button,is_android_feed_seen_state,ig_android_dense_feed_unit_cards,ig_android_drafts_video_universe,ig_android_exoplayer,ig_android_add_to_last_post,ig_android_ad_remove_cta_chevron_universe,ig_android_ad_comment_cta_universe,ig_android_search_event_icon,ig_android_channels_home,ig_android_feed,ig_android_dv2_realtime_private_share,ig_android_non_square_first,ig_android_video_interleaved_v2,ig_android_video_cache_policy,ig_android_react_native_universe_kill_switch,ig_android_video_captions_universe,ig_android_follow_search_bar,ig_android_last_edits,ig_android_two_step_capture_flow,ig_android_video_download_logging,ig_android_share_link_to_whatsapp,ig_android_facebook_twitter_profile_photos,ig_android_swipeable_filters_blacklist,ig_android_ad_pbia_profile_tap_universe,ig_android_use_software_layer_for_kc_drawing_universe,ig_android_react_native_ota,ig_android_direct_mutually_exclusive_experiment_universe,ig_android_following_follower_social_context&id=8be8aceb5c544c8c8191e86cf6bb30ce&%7B%22_csrftoken%22%3A%22Gi24BfB4TFzf3AiSB1srk74vAheVqmvy%22%2C%22_uid%22%3A%224630791068%22%2C%22_uuid%22%3A%22ac120e12056e44ad9a91bfa3064d5dc0%22%7D

````
Can you find my mistake?

**Comment by ahmdrz** [comment]
Salam pooya jan...

```php
            return $this->request('qe/sync/')
            ->addPost('_uuid', $this->uuid)
            ->addPost('_uid', $this->username_id)
            ->addPost('_csrftoken', $this->token)
            ->addPost('id', $this->username_id)
            ->addPost('experiments', Constants::EXPERIMENTS)
            ->getResponse(new SyncResponse());
```

still is not the same as 

```go
   bytes, err := json.Marshal(map[string]interface{}{
    "_uuid":      insta.Informations.UUID,
    "_uid":       insta.Informations.UsernameId,
    "_csrftoken": insta.Informations.Token,
  })

  // Because Instagram app does the same
  _, err = insta.sendRequest("qe/sync/", generateExperiments(string(bytes)), false)
  if err != nil {
    panic(err)
  }
```
***

you have to change marshalled json , see 

```go
   bytes, err := json.Marshal(map[string]interface{}{
    "_uuid":      insta.Informations.UUID,
    "_uid":       insta.Informations.UsernameId,
    "_csrftoken": insta.Informations.Token,
    "id":         insta.Informations.UsernameId,
    "experiments":GOINSTA_EXPERIMENTS,
  })
  
   _, err = insta.sendRequest("qe/sync/", generateSignature(string(bytes)), false)
  if err != nil {
    panic(err)
  }
  
```

I hope it will work.

And please do not forget to use `gofmt` for your pulled request codes.


Thank you Mr Pooya

**Comment by sourcesoft** [comment]
Hello Ahmad jan

> still is not the same as

I created a custom method having `id` and `experiments` so I didn't add it there. However I now removed the extra-no-used method and did it your way.

It's now giving no error 👍  and fetches but still have the same problem of fetching the old one just like we discussed in the issue.

> And please do not forget to use gofmt for your pulled request codes.

Sorry this was my first time contributing to a Go repo 😄  I'm using it now, thank you.

**Comment by sourcesoft** [comment]
After a few tests it's now giving me a new error 
````
panic: Invalid status code {"message": "Sorry, too many requests. Please try again later.", "status": "fail"}

````
panic here:
````
_, err = insta.sendRequest("friendships/autocomplete_user_list/?version=2", "", false)
if err != nil {
	panic(err)
}
````
This is weird

**Comment by ahmdrz** [comment]
> After a few tests it's now giving me a new error

Few month ago I was a contributor of python version of unofficial instagram api.
A lot of users tell us that have the same problem in `syncFeatures` and `autoCompleteUserList`.
You can search over issues with query "429 error code".
https://github.com/LevPasha/Instagram-API-python/issues/64

So after I saw that , I decided to make `goinsta` without those methods.

Now we have same problem as `Instagram-API-python`.

Github user , mgp25 is a advanced user in instagram api with a lot of knowledges about it.

I think if we implement `setCheckStatus` in `goinsta` we can fix this error.

Really I don't know **what the hell is going on in the Instagram** :smile:

*** 

```go
_, err = insta.sendRequest("friendships/autocomplete_user_list/?version=2", "", false)
if err != nil {
	panic(err)
}
```

I think if you check `err` value and do the same as PHP version , the bomb will be defuse :dancer:

**Comment by sourcesoft** [comment]
@ahmdrz Just did some coding and added an optional extra bool at the end of args, looks cool and works without any errors now reacting to checkStatus like PHP.

This looks good and doesn't hurt if we merge but we still have the original problem of not fetching the old feed. I think problem goes beyond these 2 methods.

**Comment by ahmdrz** [comment]
> This looks good and doesn't hurt if we merge but we still have the original problem of not fetching the old feed. I think problem goes beyond these 2 methods.

Maybe ...

Thank you Mr Pooya... :heart: 

If you detect source of problem , tell me ...


Regards

**Comment by sourcesoft** [comment]
@ahmdrz following the issue here: https://github.com/mgp25/Instagram-API/issues/955 asking PHP maintainers.

**Pull request merged**
