### PR TITLE
Add TotalUserFollowers and TotalUserFollowing

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by ahmdrz** [comment]
https://github.com/icholy/nick_bot/issues/6

> The call to SelfUserFollowing only returns the top followers. It needs to be called several times with the maxid parameters to get all the users.

Hi 
Didn't work with `SelfTotalUserFollowers` ?

**Comment by icholy** [comment]
I need all of another users followers.

**Comment by ahmdrz** [comment]
https://github.com/ahmdrz/goinsta/issues/48 
What about this one ?

**Comment by icholy** [comment]
@ahmdrz does it go into an infinite loop when trying to get all of a user's followers?

**Comment by ahmdrz** [comment]
I check it , It was okay...
There is no error and the code fetch all of users successfully.

Did you test that code ?

**Comment by icholy** [comment]
@ahmdrz the tests passed, and since `SelfTotalUserFollowers` calls `TotalUserFollowers` internally, that means it's working. So yes and no.

**Pull request merged**
