### PR TITLE
fix change primary key to int64 (fix panic on 32bit system)

### PR DESCRIPTION
**Pull request by GhostRussia**
Fix this: 
my instagram "ghost_russia", pk is 2259871196 (not int32)
```
panic: json: cannot unmarshal number 2259871196 into Go value of type int

goroutine 1 [running]:
panic(0x2477b0, 0x108a5a70)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x33c
main.main()
        /home/ghost_russia/Projects/GoPath/src/My/instaTest/main.go:20 +0x188
exit status 2
```

### CODE REVIEW

**Comment by ahmdrz** [comment]
I'm not sure about this one.
Do you know all of Instagram PK is int64 ?

**Comment by GhostRussia** [comment]
At least all User Pk is int64

**Comment by sourcesoft** [comment]
Does it mean package will no longer work on 32bit archs? Since int is smart and selects 64 only if OS is capable of it

**Comment by GhostRussia** [comment]
This code works on a 32 bit platform, I check it on a 32 bit server.
Before fixing, I was looking for a solution, here is the answer:
https://groups.google.com/forum/#!topic/golang-nuts/mtnn-01Dh_I

**Comment by GhostRussia** [comment]
goinsta

**Comment by GhostRussia** [comment]
I program directly on the 32 bit server and there I run. Server on Arm, it is installed Debian Jessie x86.
goinsta

**Comment by GhostRussia** [comment]
I program directly on the 32 bit server and there I run. Server on Arm, it is installed Debian Jessie 32bit.
goinsta
Upd: new image

**Comment by sourcesoft** [comment]
@GhostRussia using vim with tmux? same here :smile:

**Comment by ahmdrz** [comment]
@GhostRussia :||||
`./goinsta_test.go:166: cannot use user.User.Pk (type int64) as type int in argument to strconv.Itoa`
Did you run `go test -v ./...` ?

**Comment by GhostRussia** [comment]
I do not understand why Pk uses int (now int64), but in functions that require userid as string

**Comment by ahmdrz** [comment]
All test methods passed , thank you

**Comment by GhostRussia** [comment]
I'm thinking of fixing the Pk mismatch and the functions that require them, to make the functions take userid as int64

**Pull request merged**
