### PR TITLE
Proposed change to be able to change Ranked content to False in media.Next()

### PR DESCRIPTION
**Pull request by alejoloaiza**
Hi, this is to open the possibility to get media with ranked_content as false, in some cases we require media without ranking, especially for Timeline.Get() media, all comments are welcome.

### CODE REVIEW

**Comment by themester** [comment]
https://github.com/ahmdrz/goinsta/pull/130/commits/ea384f7dc7ee95020f1fb65e9cbbe97474023dd3#diff-09c503850bbb59b2a99691b045ef205bR760 

Well, but can you add a bool parameter in switch? something like:
```go
switch s := param.(type) {
  case string:
    ...
  case bool:
    if !s {
      ranked = "false"
    }
}
```

**Comment by alejoloaiza** [comment]
Sure... i'll do that

**Comment by themester** [comment]
And if you can add a comment on the function specifying the valid arguments.

**Comment by alejoloaiza** [comment]
Hi @themester, Done.

**Pull request merged**
