### PR TITLE
add location feed

### PR DESCRIPTION
**Pull request by rakd**
* GetLocationFeed()

### CODE REVIEW

**Comment by ahmdrz** [comment]
Please remove comment in your code.
https://github.com/ahmdrz/goinsta/pull/24/commits/f4a07c4cf18a71df2d853a164e24fe2059469876#diff-b6d33ead2ad4ef12fddf99bf0f7b455eR450

And format your code with `gofmt`.

https://github.com/ahmdrz/goinsta/pull/24/commits/f4a07c4cf18a71df2d853a164e24fe2059469876#diff-b6d33ead2ad4ef12fddf99bf0f7b455eR463

***

Nice dude, thank you , change your code and I will merge it. :heart:

**Comment by rakd** [comment]
oops, i've missed it. I'll fix it and commit/push later. thanks for reviewing anyway. @ahmdrz

**Comment by rakd** [comment]
thanks, fixed it. plz kindly review it again. @ahmdrz

**Comment by ahmdrz** [comment]
Thank you

**Pull request merged**
